# cloudbuild.yaml - place this file in the root of your 'my-trading-platform' directory
steps:
# Step 0: Pre-build check to ensure critical files exist.
# This prevents a successful build of a broken service.
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Check for AI Model'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'if [ ! -f api/trading_model.pkl ]; then echo "ERROR: AI model file api/trading_model.pkl not found!"; exit 1; fi'

# Step 1: Build the image using Google Cloud Buildpacks.
# This builder automatically detects the Python environment and uses project.toml
# to install system packages like chromium-driver.
- name: 'gcr.io/k8s-skaffold/pack'
  id: Build
  entrypoint: pack
  args: [
    'build',
    'asia-south1-docker.pkg.dev/$PROJECT_ID/my-trading-repo/my-trading-platform-image:latest',
    '--builder=gcr.io/buildpacks/builder:latest',
    '--path=.'
  ]

# Step 2: Push the Docker image to Google Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: [
    'push',
    'asia-south1-docker.pkg.dev/$PROJECT_ID/my-trading-repo/my-trading-platform-image:latest'
  ]

# Step 3: Deploy the container to a private Cloud Run service.
- name: 'gcr.io/google-cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'datradingplatform', # Target your existing Cloud Run service.
    '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-trading-repo/my-trading-platform-image:latest',
    '--region', 'asia-south1', # Set to Mumbai for optimal performance with Indian markets.
    '--platform', 'managed',
    '--timeout', '900s', # Increase timeout to 15 minutes for slow Selenium startup
    '--cpu-boost', # Use startup CPU boost to accelerate cold starts
    '--no-allow-unauthenticated', # Make the service private, invokable only by authenticated requests.
    '--memory', '2Gi', # Increase memory for Selenium and data processing
    '--cpu', '1',      # Allocate 1 dedicated vCPU for better performance
    '--min-instances', '1', # Keep one instance warm to prevent cold start timeouts for scheduled jobs.
    # Force the startup command to override any Procfile or buildpack ambiguity.
    '--command', 'gunicorn',
    # Add worker/thread settings and disable worker timeout for long-running token generation.
    '--args', '--bind,:$PORT,--workers,1,--threads,8,--timeout,0,app:app',
    # Mount secrets from Google Secret Manager as environment variables.
    # The format is 'ENV_VAR_NAME=SECRET_NAME:VERSION'.
    # You must create these secrets in Secret Manager first.
    '--set-secrets=KITE_API_KEY=KITE_API_KEY:latest',
    '--set-secrets=GOOGLE_SHEETS_CREDENTIALS=GOOGLE_SHEETS_CREDENTIALS:latest',
    '--set-secrets=TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest',
    '--set-secrets=TELEGRAM_CHAT_ID=TELEGRAM_CHAT_ID:latest',
    '--set-secrets=KITE_ACCESS_TOKEN=KITE_ACCESS_TOKEN:latest',
    '--set-secrets=KITE_API_SECRET=KITE_API_SECRET:latest',
    '--set-secrets=KITE_USER_ID=KITE_USER_ID:latest',
    '--set-secrets=KITE_PASSWORD=KITE_PASSWORD:latest',
    '--set-secrets=KITE_TOTP_SECRET=KITE_TOTP_SECRET:latest'
  ]

# This section lists the images that were built and pushed.
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-trading-repo/my-trading-platform-image:latest'