steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/datradingplatform', '.' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'datradingplatform'
  - '--image'
  - 'gcr.io/$PROJECT_ID/datradingplatform'
  - '--region'
  - 'asia-south1'
  - '--port'
  - '8080'
  - '--command'
  - 'gunicorn'
  - '--args'
  - '--bind=0.0.0.0:8080'
  - '--args'
  - 'app:app'
images:
- 'gcr.io/$PROJECT_ID/datradingplatform'