name: Auto Deploy & Start System

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 3 * * 1-5'  # 9:00 AM IST daily restart
  workflow_dispatch:

jobs:
  deploy-and-start:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r api/requirements.txt
    
    - name: Run system health check
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        KITE_API_KEY: ${{ secrets.KITE_API_KEY }}
        KITE_ACCESS_TOKEN: ${{ secrets.KITE_ACCESS_TOKEN }}
        KITE_API_SECRET: ${{ secrets.KITE_API_SECRET }}
        KITE_USER_ID: ${{ secrets.KITE_USER_ID }}
        KITE_PASSWORD: ${{ secrets.KITE_PASSWORD }}
        KITE_TOTP_SECRET: ${{ secrets.KITE_TOTP_SECRET }}
      run: |
        python3 immediate_health_check.py
        echo "✅ System deployment check completed"