name: Pre-Market System Check

on:
  schedule:
    - cron: '45 3 * * 1-5'  # 9:15 AM IST weekdays (3:45 AM UTC)
  workflow_dispatch:

jobs:
  pre-market-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install -r api/requirements.txt
    
    - name: Run pre-market check
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        KITE_API_KEY: ${{ secrets.KITE_API_KEY }}
        KITE_ACCESS_TOKEN: ${{ secrets.KITE_ACCESS_TOKEN }}
      run: python3 pre_market_check.py