name: Live AI Trading System
on:
  schedule:
    - cron: '*/10 4-11 * * 1-5'  # Every 10 minutes during market hours (UTC+5:30 = IST)
  workflow_dispatch:

jobs:
  ai-trading:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
        
      - name: Check Market Hours
        id: market_check
        run: |
          python -c "
          from datetime import datetime
          import pytz
          ist = pytz.timezone('Asia/Kolkata')
          now = datetime.now(ist)
          is_market_hours = 9 <= now.hour < 16 and now.weekday() < 5
          print(f'market_open={is_market_hours}'.lower())
          " >> $GITHUB_OUTPUT
        
      - name: Run Enhanced AI Trading System
        if: steps.market_check.outputs.market_open == 'true'
        run: python automated_accurate_system.py
        env:
          KITE_API_KEY: ${{ secrets.KITE_API_KEY }}
          KITE_API_SECRET: ${{ secrets.KITE_API_SECRET }}
          KITE_USER_ID: ${{ secrets.KITE_USER_ID }}
          KITE_TOTP_SECRET: ${{ secrets.KITE_TOTP_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AI_MODEL_PATH: api/enhanced_trading_model.pkl

      - name: Update Trading Data
        if: steps.market_check.outputs.market_open == 'true'
        run: |
          git config --global user.name 'AI Trading Bot'
          git config --global user.email 'ai-bot@trading-platform.com'
          git add data/ || true
          git commit -m "📊 Update live trading data - $(date)" || true
          git push || true
