name: Live AI Trading System
on:
  schedule:
    - cron: '*/10 4-11 * * 1-5'  # Every 10 minutes during market hours (UTC+5:30 = IST)
  workflow_dispatch:

jobs:
  ai-trading:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
        
      - name: Check Market Hours
        id: market_check
        run: |
          python -c "
          from datetime import datetime
          import pytz
          ist = pytz.timezone('Asia/Kolkata')
          now = datetime.now(ist)
          is_market_hours = 9 <= now.hour < 16 and now.weekday() < 5
          print(f'market_open={is_market_hours}'.lower())
          " >> $GITHUB_OUTPUT
        
      - name: Generate and Send Trading Signals
        if: steps.market_check.outputs.market_open == 'true'
        run: python3 -m api.kite_live_engine
        env:
          KITE_API_KEY: ${{ secrets.KITE_API_KEY }}
          KITE_API_SECRET: ${{ secrets.KITE_API_SECRET }}
          KITE_USER_ID: ${{ secrets.KITE_USER_ID }}
          KITE_TOTP_SECRET: ${{ secrets.KITE_TOTP_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          KITE_ACCESS_TOKEN: ${{ secrets.KITE_ACCESS_TOKEN }}
          PYTHONPATH: .

      - name: Send Status Alert
        if: steps.market_check.outputs.market_open == 'true'
        run: |
          python3 -c "
          import requests, os
          from datetime import datetime
          bot_token = os.getenv('TELEGRAM_BOT_TOKEN')
          admin_id = '1375236879'
          message = f'🚀 LIVE TRADING CYCLE COMPLETED\n⏰ {datetime.now().strftime("%H:%M:%S")}\n✅ Signals generated and sent'
          requests.post(f'https://api.telegram.org/bot{bot_token}/sendMessage', json={'chat_id': admin_id, 'text': message})
          "
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      
      - name: Update Trading Data
        if: steps.market_check.outputs.market_open == 'true'
        run: |
          git config --global user.name 'AI Trading Bot'
          git config --global user.email 'ai-bot@trading-platform.com'
          git add data/ || true
          git commit -m "📊 Update live trading data - $(date)" || true
          git push || true
