name: Test Authentication

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [main]

jobs:
  test-auth:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install kiteconnect requests gspread google-auth-oauthlib

    - name: Test Authentication
      env:
        KITE_API_KEY: ${{ secrets.KITE_API_KEY }}
        KITE_ACCESS_TOKEN: ${{ secrets.KITE_ACCESS_TOKEN }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: python test_auth.py