name: Backend Tests

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [main]

jobs:
  test-auth:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
        pip install -r requirements-automation.txt

    - name: Test Authentication
      env:
        KITE_API_KEY: ${{ secrets.KITE_API_KEY }}
        KITE_API_SECRET: ${{ secrets.KITE_API_SECRET }}
        KITE_USER_ID: ${{ secrets.KITE_USER_ID }}
        KITE_PASSWORD: ${{ secrets.KITE_PASSWORD }}
        KITE_TOTP_SECRET: ${{ secrets.KITE_TOTP_SECRET }}
      run: python -m test_auth