name: System Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  health-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: System Health Check
        run: |
          python -c "
          import os
          from datetime import datetime
          
          # Check if enhanced model exists
          model_exists = os.path.exists('api/enhanced_trading_model.pkl')
          
          # Check data freshness
          signals_exists = os.path.exists('data/signals.json')
          
          health_status = {
              'timestamp': datetime.now().isoformat(),
              'enhanced_model': model_exists,
              'signals_data': signals_exists,
              'status': 'healthy' if model_exists and signals_exists else 'needs_attention'
          }
          
          print(f'System Status: {health_status["status"]}')  
          print(f'Enhanced Model: {"✅" if model_exists else "❌"}')  
          print(f'Signals Data: {"✅" if signals_exists else "❌"}')  
          
          # Write status file
          import json
          with open('data/system_health.json', 'w') as f:
              json.dump(health_status, f, indent=2)
          "

      - name: Commit health status
        run: |
          git config --global user.name 'System Monitor'
          git config --global user.email 'monitor@trading-platform.com'
          git add data/system_health.json || true
          git commit -m "📊 System health check - $(date)" || true
          git push || true