name: Live Data and AI Training

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # For live data updates
    - cron: '0 0 * * 0' # For weekly model training

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run live bot
        env:
          KITE_API_KEY: ${{ secrets.KITE_API_KEY }}
          KITE_API_SECRET: ${{ secrets.KITE_API_SECRET }}
          KITE_USER_ID: ${{ secrets.KITE_USER_ID }}
          KITE_PASSWORD: ${{ secrets.KITE_PASSWORD }}
          KITE_TOTP_SECRET: ${{ secrets.KITE_TOTP_SECRET }}
        run: python -m api.run_live_bot

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update live data"
          file_pattern: "data/*.json"

  train-and-validate:
    if: github.event.schedule == '0 0 * * 0' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install -r requirements-automation.txt # For backtesting

      - name: Prepare Training Data
        run: python -m api.prepare_training_data

      - name: Retrain AI Model
        run: python -m api.train_model

      - name: Validate New Model with Backtest
        run: python backtest.py

      - name: Commit and Push Updated Model
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(AI): Automatically retrain and update AI model"
          file_pattern: "api/trading_model.pkl api/confusion_matrix.png api/feature_importance.png"
